name: Auto Assign Teams Based on Directory Changes

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  assign-teams:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Get changed files
        uses: actions/github-script@v7
        id: get-changes
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const files = await github.paginate(
              github.rest.pulls.listFiles,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number
              }
            );

            const changedDirs = new Set();

            for (const file of files) {
              const topDir = file.filename.split('/')[0];
              changedDirs.add(topDir);
            }

            return Array.from(changedDirs);

      - name: Test assigning backend team
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
      
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              team_reviewers: ['Palvient/backend']  // ✅ No "@"
            });
      
            console.log('Requested review from Palvient/backend');

